services:
  go:
    container_name: go-scraper
    image: agency-scraper:develop
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app